name: Lint & Format

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install
      - name: Run eslint
        run: |
          pnpm run lint
      - name: Check formatting
        run: |
          pnpm run format:check
